config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do

    root "static_pages#home"
    devise_for :users
    get "/contact", to: "static_pages#contact"
    get "/products", to: "products#index"
    get "/carts", to: "carts#index"
    post "/add_to_cart", to: "carts#create", as: "add_to_cart"
    delete "/remove_from_cart/:id", to: "carts#destroy", as: "remove_from_cart"
    post "/update_cart", to: "carts#update"
    get "/list_orders", to: "orders#index"
    get "/checkout", to: "orders#new"
    patch "/cancel/:id", to: "orders#update", as: "cancel"

    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registrations#new"
    end

    resources :orders, only: :create

    resources :products, only: :show
    namespace :admin do
      root "categories#index"
      resources :categories
      resources :products
      resources :users, only: :index
      resources :orders, only: %i(index show update)
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_checkout_products.html.erb
<li>
  <%= product.name %>
  <span>
    <%= number_to_currency price_item_cart(product.price, quantity) %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li class="alert alert-danger"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="footer__about">
        <div class="footer__about__logo">
        </div>
        <ul>
          <li><%= t "address" %></li>
          <li><%= t "phone" %></li>
          <li><%= t "email" %></li>
        </ul>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
      <div class="footer__widget">
        <ul>
          <li>
            <%= link_to t("home"), root_path %>
          </li>
        </ul>
        <ul>
          <li>
            <%= link_to t("contact"), root_path %>
          </li>
        </ul>
        <ul>
          <li>
            <%= link_to t("login"), login_path %>
          </li>
        </ul>
        <ul>
          <li>
            <%= link_to t("product"), products_path %>
          </li>
        </ul>
        <ul>
          <li>
            <%= link_to t("cart"), carts_path %>
          </li>
        </ul>
        <ul>
          <li>
            <%= link_to t("orders"), list_orders_path %>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-lg-4 col-md-12">
      <div class="footer__widget">
        <h6><%= t "get_email" %></h6>
        <p>"<%= t "get_email_send" %></p>
        <form action="#">
          <input type="text" placeholder="Enter your mail">
          <button type="submit" class="site-btn">Subscribe</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<!-- Header Section Begin -->
<div class="header__top">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6">
          <div class="header__top__left">
            <ul>
              <li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
              <li><%= t "free_ship" %></li>
            </ul>
          </div>
      </div>
        <div class="col-lg-6 col-md-6">
          <div class="header__top__right">
            <div class="header__top__right__language">
              <%= image_tag "language.png" %>
              <div><%= t "language" %></div>
              <span class="arrow_carrot-down"></span>
              <ul>
                <li><%= link_to t("english"), locale:"en" %></li>
                <li><%= link_to t("vietnamese"), locale:"vi" %></li>
              </ul>
            </div>
            <div class="header__top__right__language">
              <i class="fa fa-user"></i>
              <span class="arrow_carrot-down"></span>
              <ul>
                <li><%= link_to t("login"), login_path %></li>
                <% if user_signed_in? %>
                  <li>
                    <%= link_to t("logout"), logout_path,
                      method: :delete %>
                  </li>
                  <li>
                    <%= link_to t("edit_profile"), edit_user_registration_path %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <div class="header__logo">
        <%= link_to root_path do%>
          <%= image_tag "logo.png" %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-6">
      <nav class="header__menu">
        <ul>
          <li><%= link_to t("home"), root_path %></li>
          <li><%= link_to t("product"), products_path %></li>
          <li><%= link_to t("cart"), carts_path %>
            <ul class="header__menu__dropdown">
              <li><%= link_to t("cart"), carts_path %></li>
              <li><%= link_to t("orders"), list_orders_path %></li>
            </ul>
          </li>
          <li><%= link_to t("contact"), contact_path %></li>
        </ul>
      </nav>
    </div>
    <div class="col-lg-3">
      <div class="header__cart">
        <ul>
          <li>
            <%= link_to carts_path do %>
              <i class="fa fa-shopping-bag"></i>
              <span>
                <%= current_carts.count %>
              </span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="humberger__open">
    <i class="fa fa-bars"></i>
  </div>
</div>

app/views/shared/_header_admin.html.erb
<nav class="t-header">
  <div class="t-header-brand-wrapper">
    <%= link_to admin_root_path do %>
      <%= image_tag "logo.png" %>
    <% end %>
  </div>
  <div class="t-header-content-wrapper">
    <div class="t-header-content">
      <ul class="nav ml-auto">
        <li class="nav-item">
          <%= link_to logout_path, method: :delete, class: "btn" do %>
            <i class="fa-solid fa-right-from-bracket"></i>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="notificationDropdown"
            data-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-language"></i>
          </a>
          <div class="dropdown-menu navbar-dropdown dropdown-menu-right"
            aria-labelledby="notificationDropdown">
            <div class="dropdown-header">
              <h6 class="dropdown-title">
                <%= t "language" %>
              </h6>
            </div>
            <div class="dropdown-body">
              <div class="dropdown-list">
                <%= link_to t("vietnamese"), locale:"vi" %>
              </div>
              <div class="dropdown-list">
                <%= link_to t("english"), locale:"en" %>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_hero.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <div class="hero__categories">
        <div class="hero__categories__all">
          <i class="fa fa-bars"></i>
          <span><%= t "department" %></span>
        </div>
        <ul>
          <% @categories.each do |category| %>
            <li><%= link_to category.name, products_path(q: {category_id_eq: category.id}) %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-lg-9">
      <div class="hero__search">
        <div class="hero__search__form">
          <%= search_form_for Product.ransack(params[:q]), url: products_path do |f| %>
            <div class="hero__search__categories">
              <%= t "categories" %>
              <span class="arrow_carrot-down"></span>
            </div>
            <%= f.text_field :name_cont, placeholder: "What do yo u need?" %>
            <%= f.button t("search"), type: "submit", class: "site-btn" %>
          <% end %>
        </div>
        <div class="hero__search__phone">
          <div class="hero__search__phone__icon">
            <i class="fa fa-phone"></i>
          </div>
          <div class="hero__search__phone__text">
            <h5>+65 11.188.888</h5>
            <span><%= t "support" %></span>
          </div>
        </div>
        <div class="hero__item set-bg">
          <div class="hero__text">
            <span>
              <%= t "fresh" %>
            </span>
            <h2>
              <%= t "from_sea" %>
            </h2>
            <p>
              <%= t "free" %>
            </p>
            <%= link_to t("shop_now"), products_path, class: "primary-btn" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_item_product.html.erb
<div class="col-lg-4 col-md-4 col-sm-6">
  <div class="featured__item">
    <div class="featured__item__pic set-bg">
      <%= display_image product %>
      <ul class="featured__item__pic__hover">
        <li>
          <%= link_to product do %>
            <i class="fa-solid fa-circle-info"></i>
          <% end %>
        </li>
        <li>
          <%= link_to add_to_cart_path(id: product.id, quantity: 1), method: :post do %>
            <i class="fa fa-shopping-cart"></i>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="featured__item__text">
      <h6>
      <%= link_to product.name, product %>
      </h6>
      <h5>
        <%= "#{number_to_currency product.price} / #{product.unit}" %>
      </h5>
      </div>
  </div>
</div>

app/views/shared/_list_orders.html.erb
<tr>
  <td>
    <h5><%= order.id %></h5>
  </td>

  <td class="shoping__cart__product">
    <% order.order_details.each do |detail| %>
      <p>
        <%= "#{detail.product.name}x#{detail.quantity}
          (#{number_to_currency detail.price} / #{detail.unit})" %>
      </p>
    <% end %>
  </td>
  <td>
    <%= order.status %>
  </td>
  <td class="shoping__cart__price">
    <%= number_to_currency total_order(order) %>
  </td>
  <td>
    <% if check_status order %>
      <%= link_to t("cancel"), cancel_path(order.id),
        method: :patch, class: "btn btn-warning",
        data: {confirm: "You sure?"} %>
    <% end %>
    &nbsp;
  </td>
</tr>

app/views/shared/_products_cart.html.erb
<tr id="<%= product.id %>">
  <td class="shoping__cart__item">
    <h5><%= link_to product.name, product %></h5>
  </td>
  <td class="shoping__cart__price">
    <%= product.price %>
  </td>
  <td class="shoping__cart__price">
    <%= product.unit %>
  </td>
  <td class="shoping__cart__quantity">
    <div class="quantity">
      <div class="pro-qty">
        <input type="number" id="quantity"
          max="<%= product.quantity %>"
          min="1"
          data-id="<%= product.id %>"
          value="<%= quantity %>">
      </div>
    </div>
  </td>
  <td class="shoping__cart__total"
    data-money="<%= number_to_currency(price_item_cart product.price, quantity) %>">
    <%= number_to_currency(price_item_cart product.price, quantity) %>
  </td>
  <td class="shoping__cart__item__close">
    <span class="icon_close">
      <%= link_to remove_from_cart_path(product.id), method: :delete do %>
        <i class="fa-solid fa-xmark"></i>
      <% end %>
    </span>
  </td>
</tr>

app/views/shared/_sidebar_admin.html.erb
<div class="sidebar">
  <div class="user-profile">
    <div class="info-wrapper">
      <p class="user-name"><%= current_user.name %></p>
    </div>
  </div>
  <ul class="navigation-menu">
    <li class="nav-category-divider"><%= t "main" %></li>
    <li>
      <%= link_to root_path do %>
        <span class="link-title"><%= t "dashboard" %></span>
        <i class="fa-solid fa-gauge"></i>
      <% end %>
    </li>
    <li>
      <%= link_to admin_categories_path do %>
        <span class="link-title"><%= t "categories" %></span>
        <i class="fa-solid fa-gauge"></i>
      <% end %>
    </li>
    <li>
      <%= link_to admin_products_path do %>
        <span class="link-title"><%= t "products" %></span>
        <i class="fa-solid fa-fish"></i>
      <% end %>
    </li>
    <li>
      <%= link_to admin_users_path do %>
        <span class="link-title"><%= t "users" %></span>
        <i class="fa-solid fa-users"></i>
      <% end %>
    </li>
    <li>
      <%= link_to admin_orders_path do %>
        <span class="link-title"><%= t "orders" %></span>
        <i class="fa-solid fa-box-open"></i>
      <% end %>
    </li>
  </ul>
</div>