config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do

    root "static_pages#home"
    devise_for :users
    get "/contact", to: "static_pages#contact"
    get "/products", to: "products#index"
    get "/carts", to: "carts#index"
    post "/add_to_cart", to: "carts#create", as: "add_to_cart"
    delete "/remove_from_cart/:id", to: "carts#destroy", as: "remove_from_cart"
    post "/update_cart", to: "carts#update"
    get "/list_orders", to: "orders#index"
    get "/checkout", to: "orders#new"
    patch "/cancel/:id", to: "orders#update", as: "cancel"

    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registrations#new"
    end

    resources :orders, only: :create

    resources :products, only: :show
    namespace :admin do
      root "categories#index"
      resources :categories
      resources :products
      resources :users, only: :index
      resources :orders, only: %i(index show update)
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :load_product_with_quantity, only: %i(create update)
  def index
    @products_in_cart = {}

    current_carts.each do |id, quantity|
      product = load_product_in_cart id
      @products_in_cart[product] = quantity.to_i
    end
  end

  def create
    if @quantity.positive? && @quantity < @product.quantity
      add_to_cart params[:id], params[:quantity]
      flash[:success] = t "success"
    else
      flash[:warning] = t "fails"
    end
    redirect_to carts_path
  end

  def update
    update_quantity_cart params[:id], params[:quantity]
    respond_to do |format|
      format.js
    end
  end

  def destroy
    delete_item_cart params[:id]
    redirect_to carts_path
  end

  private
  def add_to_cart id, quantity
    current_carts[id] = if current_carts.key?(id)
                          current_carts[id] + quantity.to_i
                        else
                          quantity.to_i
                        end
  end

  def update_quantity_cart id, quantity
    current_carts[id] =
      current_carts.key?(id) ? quantity.to_i : Settings.quantity
  end

  def load_product_with_quantity
    @product = Product.find_by id: params[:id]
    @quantity = params[:quantity].to_i
    return if @product && @quantity

    flash[:danger] = t "not_found"
    redirect_to carts_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_carts
    session[:carts] ||= {}
  end

  def price_item_cart price, quantity
    quantity * price
  end

  def total_money_cart
    total = 0
    current_carts.each do |id, quantity|
      product = load_product_in_cart id
      total_item = price_item_cart product.price, quantity.to_i
      total += total_item
    end
    total
  end

  def load_product_in_cart id
    product = Product.find_by(id: id)
    return product if product.present?

    flash[:danger] = t "not_found"
    delete_item_cart id
  end

  def delete_item_cart id
    return unless current_carts.key?(id)

    current_carts.delete(id)
  end
end

app/views/carts/index.html.erb
<!-- Shoping Cart Section Begin -->
<% provide :title, t("carts") %>
<section class="shoping-cart spad">
<div class="container">
  <div class="row">
      <div class="col-lg-12">
        <div class="shoping__cart__table">
          <table>
            <thead>
              <tr>
                <th class="shoping__product">
                  <%= t "product" %>
                </th>
                <th><%= t "price" %></th>
                <th><%= t "unit" %></th>
                <th><%= t "quantity" %></th>
                <th><%= t "total" %></th>
                <th></th>
              </tr>
            </thead>
              <tbody id="products_cart">
                <% @products_in_cart.each do |product, quantity|%>
                  <%= render partial: "shared/products_cart", locals: {product: product, quantity: quantity} %>
                <% end %>
              </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="shoping__cart__btns">
          <%= link_to t("continue_shopping"), products_path, class: "primary-btn cart-btn" %>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="shoping__checkout">
          <h5><%= t "cart_total" %></h5>
          <ul>
            <li><%= t "subtotal" %> <span id="subtotal"><%= number_to_currency total_money_cart %></span></li>
            <li><%= t"total" %> <span id="total"><%= number_to_currency total_money_cart %></span></li>
          </ul>
          <%= link_to t("checkout"), checkout_path, class: "primary-btn" %>
        </div>
      </div>
    </div>
</div>
</section>
<!-- Shoping Cart Section End -->

app/views/carts/update.js.erb
$('#<%= @product.id %> .shoping__cart__total').html('<%= number_to_currency(price_item_cart @product.price, @quantity) %>');
$('#<%= @product.id %> .shoping__cart__total').data('money', '<%= number_to_currency(price_item_cart @product.price, @quantity) %>');
$('#subtotal').html('<%= number_to_currency total_money_cart %>');
$('#total').html('<%= number_to_currency total_money_cart %>');