config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do

    root "static_pages#home"
    devise_for :users
    get "/contact", to: "static_pages#contact"
    get "/products", to: "products#index"
    get "/carts", to: "carts#index"
    post "/add_to_cart", to: "carts#create", as: "add_to_cart"
    delete "/remove_from_cart/:id", to: "carts#destroy", as: "remove_from_cart"
    post "/update_cart", to: "carts#update"
    get "/list_orders", to: "orders#index"
    get "/checkout", to: "orders#new"
    patch "/cancel/:id", to: "orders#update", as: "cancel"

    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registrations#new"
    end

    resources :orders, only: :create

    resources :products, only: :show
    namespace :admin do
      root "categories#index"
      resources :categories
      resources :products
      resources :users, only: :index
      resources :orders, only: %i(index show update)
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  load_and_authorize_resource
  def index
    @pagy, @category = pagy Category.all, items: Settings.item_per_page
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "success"
      redirect_to admin_categories_url
    else
      flash[:danger] = t "create_fail"
      render :new
    end
  end

  def edit; end

  def update
    if @category.update category_params
      flash[:success] = t "success"
      redirect_to admin_categories_url
    else
      render :edit
    end
  end

  def destroy
    if @category.products.present?
      flash[:warning] = t "product_still_have"
    elsif @category.destroy
      flash[:success] = t "success"
    else
      flash[:danger] = t "fails"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.id %></td>
  <td><%= category.name %></td>
  <td><%= category.products.size %></td>
  <td class="actions">
    <%= link_to edit_admin_category_path(category.id) do %>
      <i class="fa-solid fa-wrench"></i>
    <% end %>
    <%= link_to admin_category_path(category.id), method: :delete do %>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>
  </td>
  <td class="actions">
    <i class="fa-solid fa-ellipsis-vertical"></i>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group row showcase_row_area">
    <div class="col-md-3 showcase_text_area">
      <%= f.label :name, class: "required" %>
    </div>
    <div class="col-md-9 showcase_content_area">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-sm btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :button_text, t("save") %>
<div class="col-lg-6 equel-grid">
  <div class="grid">
    <p class="grid-header"><%= t "edit_category" %></p>
    <div class="grid-body">
      <div class="item-wrapper">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<h2><%= t "list_cat" %></h2>

<div class="row">
  <div class="col-lg-10">
    <div class="grid">
      <h5 class="grid-header">
        <%= link_to t("new_category"), new_admin_category_path %>
      </h5>
      <div class="item-wrapper">
        <div class="table-responsive">
          <table class="table info-table table-striped">
            <thead>
              <tr>
                <th><%= t "cat_id" %></th>
                <th><%= t "cat_name" %></th>
                <th><%= t "num_product" %></th>
                <th><%= t "action" %></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= render @category %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<% provide :button_text, t("create") %>
<div class="col-lg-6 equel-grid">
  <div class="grid">
    <p class="grid-header"><%= t "new_category" %></p>
    <div class="grid-body">
      <div class="item-wrapper">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>