config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do

    root "static_pages#home"
    devise_for :users
    get "/contact", to: "static_pages#contact"
    get "/products", to: "products#index"
    get "/carts", to: "carts#index"
    post "/add_to_cart", to: "carts#create", as: "add_to_cart"
    delete "/remove_from_cart/:id", to: "carts#destroy", as: "remove_from_cart"
    post "/update_cart", to: "carts#update"
    get "/list_orders", to: "orders#index"
    get "/checkout", to: "orders#new"
    patch "/cancel/:id", to: "orders#update", as: "cancel"

    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registrations#new"
    end

    resources :orders, only: :create

    resources :products, only: :show
    namespace :admin do
      root "categories#index"
      resources :categories
      resources :products
      resources :users, only: :index
      resources :orders, only: %i(index show update)
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  has_one_attached :image
  enum status: {activated: 0, deactivated: 1}
  scope :activated_products, ->{where status: 0}
  scope :feature_products, ->{order(created_at: :desc).limit(6)}
  scope :newest, ->{order created_at: :desc}
  scope :search_by_name,
        ->(name){where("LOWER(name) LIKE ?", "%#{name.downcase}%") if name}
  delegate :name, to: :category, prefix: :category
  validates :name,
            presence: true,
            length: {
              maximum: Settings.str_length
            }
  validates :description, presence: true
  validates :quantity,
            presence: true,
            numericality: {
              only_integer: true,
              greater_than: Settings.zero
            }
  validates :price, presence: true,
            numericality: {
              greater_than: Settings.zero
            }
  validates :unit, presence: true
  validates :image, content_type: {in: Settings.image_type},
                    size: {less_than: Settings.max_image_size.megabytes}
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  include Admin::ProductsHelper
  load_and_authorize_resource

  def index
    @q = Product.ransack params[:q]
    @product = @q.result.newest
    @pagy, @product = pagy @product, items: Settings.item_per_page
  end

  def new
    @product = Product.new
  end

  def show; end

  def edit; end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t "success"
      redirect_to admin_products_url
    else
      flash[:danger] = t "create_fail"
      render :new
    end
  end

  def update
    if @product.update product_params
      if params[:product][:status] == "deactivated"
        handle_product_exist_in_order
      end
      flash[:success] = t "success"
      redirect_to admin_products_url
    else
      flash[:danger] = t "fails"
      render :edit
    end
  end

  def destroy
    handle_product_exist_in_order
    @product.deactivated!
    flash[:success] = t "success"
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product).permit(:name,
                                    :description,
                                    :status,
                                    :price,
                                    :unit,
                                    :quantity,
                                    :category_id,
                                    :image)
  end

  def handle_product_exist_in_order
    order_details = Order.success_order_with_pro_id(@product.id)
    order_details.each(&:rejected!)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all
    @q = Product.ransack params[:q]
    @products = @q.result distinct: true
    @pagy, @products = pagy @products.activated_products,
                            items: Settings.item_per_page
  end

  def show
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = t "not_found"
    redirect_to root_path
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def status_color status
    case status.to_sym
    when :activated
      :success
    when :deactivated
      :danger
    end
  end

  def load_category_select
    Category.select(:id, :name)
  end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row mb-3">
    <div class="col-md-8 mx-auto">
      <div class="form-group row showcase_row_area">
        <div class="col-md-3 showcase_text_area">
          <%= f.label :name, class: "required" %>
        </div>
        <div class="col-md-9 showcase_content_area">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row showcase_row_area">
        <div class="col-md-3 showcase_text_area">
          <%= f.label :description, class: "required" %>
        </div>
        <div class="col-md-9 showcase_content_area">
          <%= f.text_area :description, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row showcase_row_area">
        <div class="col-md-3 showcase_text_area">
          <%= f.label :status, class: "required" %>
        </div>
        <div class="col-md-9 showcase_content_area">
          <%= f.select :status, Product.statuses.keys.to_a, {}, {class: "custom-select"} %>
        </div>
      </div>
      <div class="form-group row showcase_row_area">
        <div class="col-md-3 showcase_text_area">
          <%= f.label :price, class: "required" %>
        </div>
        <div class="col-md-9 showcase_content_area">
          <%= f.number_field :price, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row showcase_row_area">
        <div class="col-md-3 showcase_text_area">
          <%= f.label :unit, class: "required" %>
        </div>
        <div class="col-md-9 showcase_content_area">
          <%= f.text_field :unit, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row showcase_row_area">
        <div class="col-md-3 showcase_text_area">
          <%= f.label :quantity, class: "required" %>
        </div>
        <div class="col-md-9 showcase_content_area">
          <%= f.number_field :quantity, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row showcase_row_area">
        <div class="col-md-3 showcase_text_area">
          <%= f.label :category_id, class: "required" %>
        </div>
        <div class="col-md-9 showcase_content_area">
          <%= f.collection_select :category_id, load_category_select, :id, :name, {}, {class: "custom-select"} %>
        </div>
      </div>
      <div class="form-group row showcase_row_area">
        <div class="col-md-3 showcase_text_area">
          <%= f.label :image %>
        </div>
        <div class="col-md-9 showcase_content_area">
          <div class="custom-file">
            <%= f.file_field :image %>
          </div>
        </div>
      </div>
      <div class="form-group row showcase_row_area">
        <div class="col-md-3 showcase_text_area">
        </div>
        <div class="col-md-9 showcase_content_area">
          <%= f.submit yield(:button_text), class: "btn btn-sm btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td><%= product.name %></td>
  <td>
    <label class="badge badge-<%= status_color product.status %>">
      <%= product.status %>
    </label>
  </td>
  <td><%= product.price %></td>
  <td><%= product.unit %></td>
  <td><%= product.quantity %></td>
  <td class="actions">
    <%= link_to edit_admin_product_path(product.id) do %>
      <i class="fa-solid fa-wrench"></i>
    <% end %>
    <%= link_to admin_product_path(product.id), method: :delete do %>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>
  </td>
  <td class="actions">
    <%= link_to admin_product_path product do %>
      <i class="fa-solid fa-eye"></i>
    <% end %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<% provide :button_text, t("save") %>
<div class="col-lg-12">
  <div class="grid">
    <p class="grid-header"><%= t "pro_edit" %></p>
    <div class="grid-body">
      <div class="item-wrapper">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-lg-3">
    <%= search_form_for [:admin, @q], class: "t-header-search-box" do |f| %>
      <div class="input-group">
        <%= f.text_field :name_cont, placeholder: t("search_by_name") %>
        <%= f.button nil, type: "submit", class: "btn btn-primary" do %>
          <i class="fa-solid fa-circle-arrow-right"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="col-lg-12">
  <div class="grid">
    <h5 class="grid-header">
        <%= link_to t("pro_new"), new_admin_product_path %>
      </h5>
    <div class="item-wrapper">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th><%= t "pro" %></th>
              <th><%= t "pro_name" %></th>
              <th><%= t "status" %></th>
              <th><%= sort_link @q, :price, t("price") %></th>
              <th><%= t "unit" %></th>
              <th><%= sort_link @q, :quantity, t("quantity") %></th>
              <th><%= t "action" %></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render @product %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide :button_text, t("create") %>
<div class="col-lg-12">
  <div class="grid">
    <p class="grid-header"><%=t "pro_new" %></p>
    <div class="grid-body">
      <div class="item-wrapper">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="col-lg-12">
  <div class="grid">
    <p class="grid-header"><%= t "pro_details" %></p>
    <div class="grid-body">
      <div class="item-wrapper">
        <div class="row mb-3">
          <div class="col-md-5">
            <%= display_image @product %>
          </div>
          <div class="col-md-6">
            <div class="form-group row showcase_row_area">
              <div class="col-md-3 showcase_text_area">
                <b><%= t "pro" %></b>
              </div>
              <div class="col-md-9 showcase_content_area">
                <p><%= @product.id %></p>
              </div>
            </div>
            <div class="form-group row showcase_row_area">
              <div class="col-md-3 showcase_text_area">
                <b><%= t "pro_name" %></b>
              </div>
              <div class="col-md-9 showcase_content_area">
                <p><%= @product.name %></p>
              </div>
            </div>
            <div class="form-group row showcase_row_area">
              <div class="col-md-3 showcase_text_area">
                <b><%= t "description" %></b>
              </div>
              <div class="col-md-9 showcase_content_area">
                <p><%= @product.description %></p>
              </div>
            </div>
            <div class="form-group row showcase_row_area">
              <div class="col-md-3 showcase_text_area">
                <b><%= t "status" %></b>
              </div>
              <div class="col-md-9 showcase_content_area">
                <p><%= @product.status %></p>
              </div>
            </div>
            <div class="form-group row showcase_row_area">
              <div class="col-md-3 showcase_text_area">
                <b><%= t "price" %></b>
              </div>
              <div class="col-md-9 showcase_content_area">
                <p><%= @product.price %></p>
              </div>
            </div>
            <div class="form-group row showcase_row_area">
              <div class="col-md-3 showcase_text_area">
                <b><%= t "unit" %></b>
              </div>
              <div class="col-md-9 showcase_content_area">
                <p><%= @product.unit %></p>
              </div>
            </div>
            <div class="form-group row showcase_row_area">
              <div class="col-md-3 showcase_text_area">
                <b><%= t "quantity" %></b>
              </div>
              <div class="col-md-9 showcase_content_area">
                <p><%= @product.quantity %></p>
              </div>
            </div>
            <div class="form-group row showcase_row_area">
              <div class="col-md-3 showcase_text_area">
                <b><%= t "category_name" %></b>
              </div>
              <div class="col-md-9 showcase_content_area">
                <p><%= @product.category_name %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>